{
 "title": "Nirn Proxy",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "clientId",
    "query": {
     "query": "label_values(nirn_proxy_requests_count, clientId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "429s (1h)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(nirn_proxy_requests_count{status=\"429 Too Many Requests\",clientId=~\"$clientId\"})"
    }
   ]
  },
  {
   "title": "Reqs /s (curr)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(nirn_proxy_requests_count{clientId=~\"$clientId\"}[1m]))"
    }
   ]
  },
  {
   "title": "Reqs/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(nirn_proxy_requests_count{clientId=~\"$clientId\"}[1m])) by (clientId)",
     "legendFormat": "{{clientId}}"
    },
    {
     "expr": "sum(rate(nirn_proxy_requests_count{clientId=~\"$clientId\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "429",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(method, status, route) (rate(nirn_proxy_requests_count{status=\"429 Too Many Requests\",clientId=~\"$clientId\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{route}} ({{status}})"
    }
   ]
  },
  {
   "title": "5XX",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(method, status, route) (rate(nirn_proxy_requests_count{status=~\"500 Internal Server Error|501 Not Implemented|502 Bad Gateway|503 Service Unavailable|504 Gateway Timeout|505 HTTP Version Not Supported|506 Variant Also Negotiates|507 Insufficient Storage|508 Loop Detected|510 Not Extended|511 Network Authentication Required\", clientId=~\"$clientId\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{route}} ({{status}})"
    }
   ]
  },
  {
   "title": "Status codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (status) (rate(nirn_proxy_requests_count{clientId=~\"$clientId\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Reqs by path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (route) (rate(nirn_proxy_requests_count{clientId=~\"$clientId\"}[$__rate_interval]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Latency 90th",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(method, route) (nirn_proxy_requests{quantile=\"0.9\",clientId=~\"$clientId\"})",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Latency 99th",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(method, route) (nirn_proxy_requests{quantile=\"0.99\",clientId=~\"$clientId\"})",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Latency Avg",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(method, route) (nirn_proxy_requests{quantile=\"0.5\",clientId=~\"$clientId\"})",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  }
 ]
}